# Generated by Django 5.1.2 on 2025-08-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWMSmashClubWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrator',
        ),
    ]
