# Generated by Django 5.1.2 on 2025-08-03 03:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWMSmashClubWebsite', '0002_rename_admin_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Administrator',
            new_name='Administrators',
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_number', models.IntegerField(default=1)),
                ('best_of_num', models.IntegerField(default=3)),
                ('games_played', models.IntegerField(default=0)),
                ('is_winners', models.BooleanField(default=True)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_sets', to='UWMSmashClubWebsite.players')),
                ('players', models.ManyToManyField(blank=True, null=True, related_name='played_sets', to='UWMSmashClubWebsite.players')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sets', to='UWMSmashClubWebsite.players')),
            ],
        ),
    ]
