# Generated by Django 5.1.2 on 2025-08-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWMSmashClubWebsite', '0003_players_rename_administrator_administrators_matches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrators',
            new_name='Administrator',
        ),
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
