# Generated by Django 5.1.2 on 2025-08-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWMSmashClubWebsite', '0004_rename_administrators_administrator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='best_of_num',
            field=models.IntegerField(choices=[('3', 3), ('5', 5)], default=3),
        ),
    ]
