# Generated by Django 5.1.2 on 2025-08-03 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWMSmashClubWebsite', '0005_alter_match_best_of_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default='Cream City Clash #XXX')),
                ('players', models.ManyToManyField(blank=True, null=True, related_name='brackets_entered', to='UWMSmashClubWebsite.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('p1Char', models.CharField(blank=True, choices=[('Ness', 'Ness')], max_length=32, null=True)),
                ('p2Char', models.CharField(blank=True, choices=[('Ness', 'Ness')], max_length=32, null=True)),
                ('game_num', models.IntegerField(default=1)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_loser', to='UWMSmashClubWebsite.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_winner', to='UWMSmashClubWebsite.player')),
            ],
        ),
        migrations.CreateModel(
            name='SeedToPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seed', models.IntegerField(default=1, unique=True)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('bracket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UWMSmashClubWebsite.bracket')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_and_placement', to='UWMSmashClubWebsite.player')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_number', models.IntegerField(default=1)),
                ('best_of_num', models.IntegerField(choices=[('3', 3), ('5', 5)], default=3)),
                ('is_winners', models.BooleanField(default=True)),
                ('games', models.ManyToManyField(blank=True, null=True, to='UWMSmashClubWebsite.game')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_sets', to='UWMSmashClubWebsite.player')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to='UWMSmashClubWebsite.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='UWMSmashClubWebsite.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sets', to='UWMSmashClubWebsite.player')),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='matches',
            field=models.ManyToManyField(blank=True, null=True, related_name='bracket_sets', to='UWMSmashClubWebsite.set'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
