# Generated by Django 5.1.2 on 2025-08-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWMSmashClubWebsite', '0006_bracket_game_seedtoplacement_set_bracket_matches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='matches',
            field=models.ManyToManyField(related_name='bracket_sets', to='UWMSmashClubWebsite.set'),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='players',
            field=models.ManyToManyField(related_name='brackets_entered', to='UWMSmashClubWebsite.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='p1Char',
            field=models.CharField(blank=True, choices=[('Mario', 'mario'), ('Donkey Kong', 'donkey kong'), ('Link', 'link'), ('Samus', 'samus'), ('Dark Samus', 'dark samus'), ('Yoshi', 'yoshi'), ('Kirby', 'kirby'), ('Fox', 'fox'), ('Pikachu', 'pikachu'), ('Luigi', 'luigi'), ('Ness', 'ness'), ('Captain Falcon', 'captain falcon'), ('Jigglypuff', 'jigglypuff'), ('Peach', 'peach'), ('Daisy', 'daisy'), ('Bowser', 'bowser'), ('Ice Climbers', 'ice climbers'), ('Sheik', 'sheik'), ('Zelda', 'zelda'), ('Dr. Mario', 'dr. mario'), ('Pichu', 'pichu'), ('Falco', 'falco'), ('Marth', 'marth'), ('Lucina', 'lucina'), ('Young Link', 'young link'), ('Ganondorf', 'ganondorf'), ('Mewtwo', 'mewtwo'), ('Roy', 'roy'), ('Chrom', 'chrom'), ('Mr. Game & Watch', 'mr. game & watch'), ('Meta Knight', 'meta knight'), ('Pit', 'pit'), ('Dark Pit', 'dark pit'), ('Zero Suit Samus', 'zero suit samus'), ('Wario', 'wario'), ('Snake', 'snake'), ('Ike', 'ike'), ('Pokemon Trainer', 'pokemon trainer'), ('Diddy Kong', 'diddy kong'), ('Lucas', 'lucas'), ('Sonic', 'sonic'), ('King Dedede', 'king dedede'), ('Olimar', 'olimar'), ('Lucario', 'lucario'), ('R.O.B.', 'r.o.b.'), ('Toon Link', 'toon link'), ('Wolf', 'wolf'), ('Villager', 'villager'), ('Mega Man', 'mega man'), ('Rosalina & Luma', 'rosalina & luma'), ('Wii Fit Trainer', 'wii fit trainer'), ('Little Mac', 'little mac'), ('Greninja', 'greninja'), ('Palutena', 'palutena'), ('Pac-Man', 'pac-man'), ('Robin', 'robin'), ('Shulk', 'shulk'), ('Bowser Jr.', 'bowser jr.'), ('Duck Hunt', 'duck hunt'), ('Ryu', 'ryu'), ('Ken', 'ken'), ('Cloud', 'cloud'), ('Corrin', 'corrin'), ('Bayonetta', 'bayonetta'), ('Inkling', 'inkling'), ('Ridley', 'ridley'), ('Simon', 'simon'), ('Richter', 'richter'), ('King K. Rool', 'king k. rool'), ('Isabelle', 'isabelle'), ('Incineroar', 'incineroar'), ('Piranha Plant', 'piranha plant'), ('Joker', 'joker'), ('Hero', 'hero'), ('Banjo & Kazooie', 'banjo & kazooie'), ('Terry', 'terry'), ('Byleth', 'byleth'), ('Min Min', 'min min'), ('Steve', 'steve'), ('Sephiroth', 'sephiroth'), ('Pyra/Mythra', 'pyra/mythra'), ('Kazuya', 'kazuya'), ('Sora', 'sora'), ('Mii Brawler', 'mii brawler'), ('Mii Swordfighter', 'mii swordfighter'), ('Mii Gunner', 'mii gunner')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2Char',
            field=models.CharField(blank=True, choices=[('Mario', 'mario'), ('Donkey Kong', 'donkey kong'), ('Link', 'link'), ('Samus', 'samus'), ('Dark Samus', 'dark samus'), ('Yoshi', 'yoshi'), ('Kirby', 'kirby'), ('Fox', 'fox'), ('Pikachu', 'pikachu'), ('Luigi', 'luigi'), ('Ness', 'ness'), ('Captain Falcon', 'captain falcon'), ('Jigglypuff', 'jigglypuff'), ('Peach', 'peach'), ('Daisy', 'daisy'), ('Bowser', 'bowser'), ('Ice Climbers', 'ice climbers'), ('Sheik', 'sheik'), ('Zelda', 'zelda'), ('Dr. Mario', 'dr. mario'), ('Pichu', 'pichu'), ('Falco', 'falco'), ('Marth', 'marth'), ('Lucina', 'lucina'), ('Young Link', 'young link'), ('Ganondorf', 'ganondorf'), ('Mewtwo', 'mewtwo'), ('Roy', 'roy'), ('Chrom', 'chrom'), ('Mr. Game & Watch', 'mr. game & watch'), ('Meta Knight', 'meta knight'), ('Pit', 'pit'), ('Dark Pit', 'dark pit'), ('Zero Suit Samus', 'zero suit samus'), ('Wario', 'wario'), ('Snake', 'snake'), ('Ike', 'ike'), ('Pokemon Trainer', 'pokemon trainer'), ('Diddy Kong', 'diddy kong'), ('Lucas', 'lucas'), ('Sonic', 'sonic'), ('King Dedede', 'king dedede'), ('Olimar', 'olimar'), ('Lucario', 'lucario'), ('R.O.B.', 'r.o.b.'), ('Toon Link', 'toon link'), ('Wolf', 'wolf'), ('Villager', 'villager'), ('Mega Man', 'mega man'), ('Rosalina & Luma', 'rosalina & luma'), ('Wii Fit Trainer', 'wii fit trainer'), ('Little Mac', 'little mac'), ('Greninja', 'greninja'), ('Palutena', 'palutena'), ('Pac-Man', 'pac-man'), ('Robin', 'robin'), ('Shulk', 'shulk'), ('Bowser Jr.', 'bowser jr.'), ('Duck Hunt', 'duck hunt'), ('Ryu', 'ryu'), ('Ken', 'ken'), ('Cloud', 'cloud'), ('Corrin', 'corrin'), ('Bayonetta', 'bayonetta'), ('Inkling', 'inkling'), ('Ridley', 'ridley'), ('Simon', 'simon'), ('Richter', 'richter'), ('King K. Rool', 'king k. rool'), ('Isabelle', 'isabelle'), ('Incineroar', 'incineroar'), ('Piranha Plant', 'piranha plant'), ('Joker', 'joker'), ('Hero', 'hero'), ('Banjo & Kazooie', 'banjo & kazooie'), ('Terry', 'terry'), ('Byleth', 'byleth'), ('Min Min', 'min min'), ('Steve', 'steve'), ('Sephiroth', 'sephiroth'), ('Pyra/Mythra', 'pyra/mythra'), ('Kazuya', 'kazuya'), ('Sora', 'sora'), ('Mii Brawler', 'mii brawler'), ('Mii Swordfighter', 'mii swordfighter'), ('Mii Gunner', 'mii gunner')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='games',
            field=models.ManyToManyField(to='UWMSmashClubWebsite.game'),
        ),
    ]
